.PHONY: clean All

All:
	@echo "----------Building project:[ Project1 - Debug ]----------"
	@cd "Workspace2" && "$(MAKE)" -f  "Project1.mk"
clean:
	@echo "----------Cleaning project:[ Project1 - Debug ]----------"
	@cd "Workspace2" && "$(MAKE)" -f  "Project1.mk" clean
